# -*- coding: utf-8 -*-
"""Stocex_nb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1il9tnnU4GzqnlHwKxhO0pj8IY5IqzPEs

## **Stocex project ipynb file.**
"""

# Code to load FinBERT model for use in next steps
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Load FinBERT model from HuggingFace
finbert_tokenizer = AutoTokenizer.from_pretrained("yiyanghkust/finbert-tone")
finbert_model = AutoModelForSequenceClassification.from_pretrained("yiyanghkust/finbert-tone")
labels = ["negative", "neutral", "positive"]

def get_finbert_sentiment(text):
    inputs = finbert_tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = finbert_model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    prediction = labels[probs.argmax()]
    return prediction, probs.max().item()

# Necessary libraries
#!pip install yfinance
import json

"""## ***Step 1*** - Retrieve latest news from NewsAPI"""

# Code to retrieve yesterday news from NewSAPI.

import requests
import datetime

NEWS_API_KEY = "c32779e494d04276b24ac0eb577c5ca2"  # My generated API key

# Function to fetch yesterday news
def fetch_yesterdays_news():
    today = datetime.datetime.utcnow().date()
    yesterday = today - datetime.timedelta(days=1)

    url = (
        f"https://newsapi.org/v2/everything?"
        f"q=stocks OR market OR earnings OR inflation OR fed&"
        f"from={yesterday}&to={yesterday}&"
        f"language=en&"
        f"sortBy=publishedAt&"
        f"pageSize=100&"
        f"apiKey={NEWS_API_KEY}"
    )

    print(f"🔍 Fetching news for {yesterday}")
    response = requests.get(url)
    data = response.json()

    if data.get("status") != "ok":
        print("❌ Error fetching news:", data)
        return []

    return data.get("articles", [])

"""##***Step 2*** - Extract Mentioned Companies from Headlines"""

import spacy
nlp = spacy.load("en_core_web_sm")

#Loading company names and tickers
import pandas as pd

def load_sp500_tickers():
    url = "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv"
    df = pd.read_csv(url)

    print("📊 Loaded columns:", df.columns.tolist())  # Debugging line

    # If the columns are wrong, fix them
    if 'Name' not in df.columns or 'Symbol' not in df.columns:
        if len(df.columns) >= 2:
            df.columns = ['Symbol', 'Name'] + list(df.columns[2:])
        else:
            raise ValueError("CSV does not have expected columns.")

    return {row['Name'].lower(): row['Symbol'] for _, row in df.iterrows()}

#Named Entity Extraction from News Headlines
def extract_companies_from_articles(articles, known_companies):
    mentioned_tickers = set()

    for article in articles:
        text = (article.get("title") or "") + " " + (article.get("description") or "")
        doc = nlp(text)

        for ent in doc.ents:
            if ent.label_ == "ORG":
                company_name = ent.text.lower()
                for known_name, ticker in known_companies.items():
                    if company_name in known_name:  # simple substring match
                        mentioned_tickers.add(ticker)

    return list(mentioned_tickers)

# Step 1: Fetch yesterday’s headlines
articles = fetch_yesterdays_news()

# Step 2: Extract tickers mentioned in news
known_companies = load_sp500_tickers()
tickers_from_news = extract_companies_from_articles(articles, known_companies)

print("🧠 Tickers mentioned in yesterday’s news:", tickers_from_news)

"""## ***Step 3*** — Sentiment Scoring (FinBERT)

Now we use FinBERT model to understands financial language and market sentiment better than general-purpose models like TextBlob or vanilla BERT.

We write a function to:

1.   Group news articles by ticker
2.   Run FinBERT on the text (headline + description)
3.   Return average sentiment score per ticker
"""

#Score Sentiment Per Ticker
from collections import defaultdict

def score_sentiment_by_ticker(articles, known_companies):
    ticker_sentiments = defaultdict(list)

    for article in articles:
        text = (article.get("title") or "") + " " + (article.get("description") or "")
        doc = nlp(text)

        orgs = [ent.text.lower() for ent in doc.ents if ent.label_ == "ORG"]
        matched_tickers = set()

        for org in orgs:
            for known_name, ticker in known_companies.items():
                if org in known_name:
                    matched_tickers.add(ticker)

        if matched_tickers:
            sentiment, confidence = get_finbert_sentiment(text)
            score = 1 if sentiment == "positive" else -1 if sentiment == "negative" else 0
            for ticker in matched_tickers:
                ticker_sentiments[ticker].append(score)

    # Format into DataFrame
    summary = []
    for ticker, scores in ticker_sentiments.items():
        avg_score = sum(scores) / len(scores)
        label = "Positive" if avg_score > 0 else "Negative" if avg_score < 0 else "Neutral"
        summary.append({
            "Ticker": ticker,
            "Mentions": len(scores),
            "Avg Sentiment Score": avg_score,
            "Sentiment Label": label
        })

    return pd.DataFrame(summary).sort_values(by="Mentions", ascending=False)

# From Step 1 & 2
articles = fetch_yesterdays_news()
known_companies = load_sp500_tickers()

# Step 2 recap
mentioned_tickers = extract_companies_from_articles(articles, known_companies)

# Step 3: FinBERT scoring
sentiment_df = score_sentiment_by_ticker(articles, known_companies)
sentiment_df

"""##***Step 4*** — Intraday Data Fetch with yfinance

## We are now going to fetch 1 month previous data from yfinance and process it into TimeGPT ##

This is what we will do:



1.   Pull 5-minute bars using yfinance
2.   Slice to past 1 month
3.   Send to TimeGPT to forecast next N bars
"""

import yfinance as yf
import pandas as pd

def fetch_intraday_data_yfinance(ticker, period_days=30):
    df = yf.download(ticker, period=f"{period_days}d", interval="5m", progress=False)

    # Flatten multi-index columns (if any)
    df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]

    # Select and format required columns
    df = df[['Close']].reset_index()
    df.rename(columns={'Datetime': 'timestamp', 'Close': 'value'}, inplace=True)
    df['timestamp'] = df['timestamp'].dt.strftime('%Y-%m-%dT%H:%M:%SZ')

    return df.to_dict(orient='records')

#Since we are using the free public TimeGPT API, nixtla does not support intraday (5-minute) data. So changing to hourly.
def resample_to_daily(series_5min):
    df = pd.DataFrame(series_5min)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df.set_index('timestamp', inplace=True)
    daily_df = df['value'].resample('1D').mean().dropna().reset_index()
    daily_df['timestamp'] = daily_df['timestamp'].dt.strftime('%Y-%m-%dT%H:%M:%SZ')
    return daily_df.to_dict(orient='records')

# Try it out
data = fetch_intraday_data_yfinance("ED", period_days=30)
print(data[:5])  # Preview

"""## ***Step 5*** - Forecast Next 1 Hour (12 Bars Ahead) with TimeGPT"""

import requests
import json

def forecast_with_timegpt(series, horizon=12):
    url = "https://api.nixtla.io/forecast"
    headers = {
        "Authorization": "Bearer nixak-oxZzNGjeG0nrFYWsOcWaehcyysm74OCuNeL2s6Y0wTX7df98QBnDEdTSce2DyO3rLL3C3bvHakkkokIS",
        "Content-Type": "application/json"
    }

    payload = {
        "series": series,
        "horizon": horizon,
        "freq": "D",
        "target": "value",
        "include_history": False
    }

    response = requests.post(url, headers=headers, data=json.dumps(payload))
    response.raise_for_status()
    result = response.json()

    return pd.DataFrame({
        "timestamp": result["timestamp"],
        "forecast": result["value"]
    })

# Step 1: Get 5-min data
series_5min = fetch_intraday_data_yfinance("ED", period_days=30)

series_daily = resample_to_daily(series_5min)
forecast_df = forecast_with_timegpt(series_daily, horizon=7)  # next 7 days

# Show forecast
print(forecast_df)

sample_series = [
    {"timestamp": "2023-01-01T00:00:00Z", "value": 100},
    {"timestamp": "2023-01-02T00:00:00Z", "value": 101},
    {"timestamp": "2023-01-03T00:00:00Z", "value": 102},
    {"timestamp": "2023-01-04T00:00:00Z", "value": 103},
    {"timestamp": "2023-01-05T00:00:00Z", "value": 104},
    {"timestamp": "2023-01-06T00:00:00Z", "value": 105},
]

forecast = forecast_with_timegpt(sample_series, horizon=3)
print(forecast)

for ticker in sentiment_df["Ticker"]:
    series = fetch_intraday_data_yfinance(ticker, period_days=30)
    print(f"Ticker: {ticker}, Data points: {len(series)}")
    print("First 2 rows:", series[:2])
    forecast = forecast_with_timegpt(series, horizon=12)
    print(f"\n📈 {ticker} Forecast:", forecast)

"""nixak-oxZzNGjeG0nrFYWsOcWaehcyysm74OCuNeL2s6Y0wTX7df98QBnDEdTSce2DyO3rLL3C3bvHakkkokIS"""

import requests
import json
import pandas as pd

def forecast_with_timegpt(series, horizon=12):
    url = "https://api.nixtla.io/forecast"
    headers = {
        "Authorization": "Bearer nixak-oxZzNGjeG0nrFYWsOcWaehcyysm74OCuNeL2s6Y0wTX7df98QBnDEdTSce2DyO3rLL3C3bvHakkkokIS",  # Ensure this API key is valid and not in demo mode
        "Content-Type": "application/json"
    }

    payload = {
        "series": series,
        "horizon": horizon,
        "freq": "D",           # Daily frequency; change if needed
        "target": "value",
        "include_history": False
    }

    # Debug print: check the payload being sent.
    print("DEBUG: Sending payload:", json.dumps(payload, indent=2))

    response = requests.post(url, headers=headers, data=json.dumps(payload))
    response.raise_for_status()
    result = response.json()

    # Debug print: check the result returned by the API.
    print("DEBUG: Received result:", json.dumps(result, indent=2))

    return pd.DataFrame({
        "timestamp": result.get("timestamp", []),
        "forecast": result.get("value", [])
    })

# Code to fetch 5-min data and resample to daily
import yfinance as yf

def fetch_intraday_data_yfinance(ticker, period_days=30):
    df = yf.download(ticker, period=f"{period_days}d", interval="5m", progress=False)
    # Flatten multi-index columns (if present)
    df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]
    df = df[['Close']].reset_index()
    # Rename the columns if necessary (adjust if the column name is different)
    df.rename(columns={'Datetime': 'timestamp', 'Close': 'value'}, inplace=True)
    # Convert timestamp to ISO format
    df['timestamp'] = pd.to_datetime(df['timestamp']).dt.strftime('%Y-%m-%dT%H:%M:%SZ')
    return df.to_dict(orient='records')

def resample_to_daily(series_5min):
    df = pd.DataFrame(series_5min)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df.set_index('timestamp', inplace=True)
    daily_df = df['value'].resample('1D').mean().dropna().reset_index()
    daily_df['timestamp'] = daily_df['timestamp'].dt.strftime('%Y-%m-%dT%H:%M:%SZ')
    return daily_df.to_dict(orient='records')

# Fetch and process data
series_5min = fetch_intraday_data_yfinance("ED", period_days=30)
print("First 5 rows of 5-min data:", series_5min[:5])

series_daily = resample_to_daily(series_5min)
print("Daily resampled data:", series_daily[:5])

forecast_df = forecast_with_timegpt(series_daily, horizon=7)  # forecast next 7 days
print("Forecast DataFrame:\n", forecast_df)

# Example using a sample series
sample_series = [
    {"timestamp": "2023-01-01T00:00:00Z", "value": 100},
    {"timestamp": "2023-01-02T00:00:00Z", "value": 101},
    {"timestamp": "2023-01-03T00:00:00Z", "value": 102},
    {"timestamp": "2023-01-04T00:00:00Z", "value": 103},
    {"timestamp": "2023-01-05T00:00:00Z", "value": 104},
    {"timestamp": "2023-01-06T00:00:00Z", "value": 105},
]

forecast_sample = forecast_with_timegpt(sample_series, horizon=3)
print("Forecast for sample_series:\n", forecast_sample)

# Process forecasts for sentiment tickers (example loop)
for ticker in sentiment_df["Ticker"]:
    series = fetch_intraday_data_yfinance(ticker, period_days=30)
    print(f"Ticker: {ticker}, Data points: {len(series)}")
    print("First 2 rows:", series[:2])
    forecast = forecast_with_timegpt(series, horizon=12)
    print(f"\n📈 {ticker} Forecast:", forecast)